"""Compile the polygon-only SVG master to allocation-free TFT triangle data.

Edit kajo_splash.svg, then run this script. Unsupported SVG features fail loudly;
convert paths/transforms to explicit polygon coordinates before exporting.
--preview renders the generated triangles and the actual TFT Font 2 caption.
"""
from __future__ import annotations
import argparse
import re
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "tools/logo/kajo_splash.svg"
HEADER = ROOT / "include/kajo_splash_generated.h"

def cross(a, b, c):
    return (b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0])

def triangulate(points):
    pts = []
    for p in points:
        if not pts or p != pts[-1]:
            pts.append(p)
    if pts[-1] == pts[0]:
        pts.pop()
    changed = True
    while changed and len(pts) > 3:
        changed = False
        for i in range(len(pts)):
            if cross(pts[i-1], pts[i], pts[(i+1)%len(pts)]) == 0:
                pts.pop(i)
                changed = True
                break
    area = sum(a[0]*b[1]-b[0]*a[1] for a,b in zip(pts, pts[1:]+pts[:1]))
    if area == 0:
        raise ValueError("zero-area polygon")
    if area < 0:
        pts.reverse()
    expected_area = abs(area)
    result = []
    while len(pts) > 3:
        for i,b in enumerate(pts):
            a,c = pts[i-1],pts[(i+1)%len(pts)]
            if cross(a,b,c) <= 0:
                continue
            if any(cross(a,b,p)>=0 and cross(b,c,p)>=0 and cross(c,a,p)>=0
                   for j,p in enumerate(pts) if j not in ((i-1)%len(pts),i,(i+1)%len(pts))):
                continue
            result.append((a,b,c))
            pts.pop(i)
            break
        else:
            raise ValueError("polygon is not simple or could not be triangulated")
    result.append(tuple(pts))
    if sum(cross(*t) for t in result) != expected_area:
        raise ValueError("triangulation changed polygon area")
    return result

def compile_art():
    svg = ET.parse(SOURCE).getroot()
    if svg.get("viewBox") != "0 0 320 240":
        raise ValueError("artwork must use the native 320x240 viewBox")
    triangles = []
    for node in svg:
        tag = node.tag.rsplit("}",1)[-1]
        if tag in ("title", "desc"):
            continue
        if tag != "polygon" or set(node.attrib)-{"id","fill","points"}:
            raise ValueError(f"unsupported SVG element/attributes: {node.attrib}")
        color = node.attrib["fill"]
        if not re.fullmatch(r"#[0-9a-fA-F]{6}",color):
            raise ValueError("only solid RGB fills are supported")
        points = [tuple(map(int,p.split(","))) for p in node.attrib["points"].split()]
        if any(len(p)!=2 or not (0<=p[0]<320 and 0<=p[1]<240) for p in points):
            raise ValueError("polygon coordinates must be integer display pixels")
        r,g,b = (int(color[i:i+2],16) for i in (1,3,5))
        rgb565 = ((r>>3)<<11)|((g>>2)<<5)|(b>>3)
        for triangle in triangulate(points):
            triangles.append((triangle,rgb565))
    return triangles

def preview(triangles, target):
    from PIL import Image, ImageDraw
    img = Image.new("RGB",(320,240))
    draw = ImageDraw.Draw(img)
    for triangle,c in triangles:
        draw.polygon(triangle,fill=(((c>>11)&31)*255//31,((c>>5)&63)*255//63,(c&31)*255//31))
    # Font data stays in its upstream library; do not duplicate it in the repo.
    font_path = ROOT / ".pio/libdeps/kajo/TFT_eSPI/Fonts/Font16.c"
    font = font_path.read_text()
    font = re.sub(r"#ifdef[^\n]*\n(.*?)#else.*?#endif",r"\1",font,flags=re.S)
    font = re.sub(r"//[^\n]*","",font)
    widths = list(map(int,re.findall(r"\d+",re.search(r"widtbl_f16\[96\].*?\{(.*?)\}",font,re.S)[1])))
    version = re.search(r'#define CYD_FIRMWARE_VERSION_NAME "([^"]+)"',(ROOT/"include/config.h").read_text())[1]
    caption = "Dash Firmware v"+version
    x = 160-sum(widths[ord(c)-32] for c in caption)//2
    for char in caption:
        raw = re.search(r"chr_f16_%02x\[\d+\].*?\{(.*?)\}"%ord(char),font,re.S|re.I)[1]
        data = [int(v,16) for v in re.findall(r"0x([0-9a-fA-F]+)",raw)]
        stride = len(data)//16
        for y in range(16):
            for dx in range(stride*8):
                if data[y*stride+dx//8] & (0x80>>(dx%8)):
                    draw.point((x+dx,212+y), fill="white")
        x += widths[ord(char)-32]
    target.parent.mkdir(parents=True,exist_ok=True)
    img.save(target)
    img.resize((960,720),Image.Resampling.NEAREST).save(target.with_name(target.stem+"_3x.png"))

def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--preview",type=Path)
    parser.add_argument("--check",action="store_true")
    args=parser.parse_args()
    triangles=compile_art()
    lines=["// Generated by tools/logo/generate_splash.py. Edit the SVG, not this file.",
           "#pragma once", "#include <stdint.h>", "namespace kajo_splash {",
           "struct Triangle { int16_t x0, y0, x1, y1, x2, y2; uint16_t color; };",
           "static const Triangle triangles[] = {"]
    for triangle,color in triangles:
        values=", ".join(str(v) for point in triangle for v in point)
        lines.append("  {"+values+", 0x%04X},"%color)
    lines.extend(["};", "}  // namespace kajo_splash", ""])
    output="\n".join(lines)
    # Compare and write bytes: text mode would turn \n into \r\n on Windows and
    # then hide that from the comparison, so the header would differ per OS.
    current=HEADER.read_bytes().decode("utf-8") if HEADER.exists() else None
    if args.check:
        if current!=output:
            raise SystemExit("Generated splash is stale; run tools/logo/generate_splash.py")
    elif current!=output:
        HEADER.write_bytes(output.encode("utf-8"))
    if args.preview:
        preview(triangles,args.preview)
    print(f"Splash: {len(triangles)} triangles, {len(triangles)*14} bytes of geometry")

if __name__ == "__main__":
    main()
