// Generated by tools/generate_changelog_header.py from CHANGELOG.md.
// Do not edit by hand: edit CHANGELOG.md and rerun the script.
//
// English only, unlike the rest of the interface. Translating changelog
// entries six ways is not worth hand-maintaining, so the headings around
// them are localised and the entries themselves are not.
#pragma once

#include <stdint.h>

struct FirmwareChangelogEntry {
  const char *date;
  const char *title;
  const char *summary;
};

static const FirmwareChangelogEntry kFirmwareChangelog[] = {
    {
        "2026-09-12",
        "Phase current in ride logs",
        "Rides now record motor phase current, and replay can chart it. VESC only for now.",
    },
    {
        "2026-09-12",
        "Ride replay",
        "Recorded rides replay on the display, with up to four charts, a summary and delete.",
    },
    {
        "2026-09-08",
        "KAJO rename",
        "The project, firmware and companion app are now KAJO, KAJO-Dash and KAJO Companion.",
    },
    {
        "2026-09-07",
        "FarDriver discovery freeze",
        "Confirming a FarDriver controller froze the display. Incoming packets rebuilt the screen.",
    },
};

static constexpr uint8_t kFirmwareChangelogCount = sizeof(kFirmwareChangelog) / sizeof(kFirmwareChangelog[0]);
