// Generated by tools/generate_changelog_header.py from CHANGELOG.md.
// Do not edit by hand: edit CHANGELOG.md and rerun the script.
//
// English only, unlike the rest of the interface. Translating changelog
// entries six ways is not worth hand-maintaining, so the headings around
// them are localised and the entries themselves are not.
#pragma once

#include <stdint.h>

struct FirmwareChangelogEntry {
  const char *date;
  const char *title;
  const char *summary;
};

static const FirmwareChangelogEntry kFirmwareChangelog[] = {
    {
        "2026-10-06",
        "Battery chemistry",
        "Battery Configuration is one page, with Li-ion, LiPo, LiFePO4 and editable cell volts.",
    },
    {
        "2026-10-06",
        "Theme previews at real time",
        "Theme previews run at 1x; fast demo rides still train gauge ranges between updates.",
    },
    {
        "2026-10-06",
        "Smoother dashboard updates",
        "Needles glide, unchanged values skip redraws, and overlay slides pause dashboard updates.",
    },
    {
        "2026-10-06",
        "Automatic gauge ranges",
        "Gauge scales learn peaks, shrink after quieter riding, and keep separate link state.",
    },
};

static constexpr uint8_t kFirmwareChangelogCount = sizeof(kFirmwareChangelog) / sizeof(kFirmwareChangelog[0]);
