#pragma once
#include <lvgl.h>

#include "app_state.h"
#include "cyd_icons_1bit.h"
#include "cyd_layout_generated.h"
#include "pixel_font.h"

// LVGL counterparts of the drawLayout* helpers in src/main.cpp. Items come
// from cyd_layout_generated.h; anchors/fonts follow the same conventions.

// Custom digits-only fonts (Rajdhani Bold: "0123456789.-") for the big
// speed readouts; generated by lv_font_conv, see lv_font_speed*.c. The 48 px
// tier gives the number ladder a step between 72 px and the 36 px UI font.
#ifdef __cplusplus
extern "C" {
#endif
LV_FONT_DECLARE(lv_font_rajdhani_10)  // smallest UI face; F10/F12 both map to 12 px
LV_FONT_DECLARE(lv_font_speed48)
LV_FONT_DECLARE(lv_font_speed72)
LV_FONT_DECLARE(lv_font_speed96)
#ifdef __cplusplus
}
#endif

const lv_font_t *layoutFontToLv(uint8_t layoutFontPx, const lv_font_t *fallback = &lv_font_rajdhani_14);

// Strips click/scroll/gesture handling from a decoration widget so touches
// always fall through to the screen (LVGL objects are clickable by default).
void makePassive(lv_obj_t *obj);

// lv_label_set_text that skips (and does not invalidate) when unchanged
void setLabelText(lv_obj_t *label, const char *text);

// LVGL 8 invalidates an object on every style write and every HIDDEN flag write,
// changed or not (lv_obj_set_pos and lv_obj_set_size already compare first). A
// dashboard update that repeats these each tick repaints those objects each tick,
// so use these in any path that runs more than once per screen build.
void setObjHidden(lv_obj_t *obj, bool hidden);
void setObjTextAlign(lv_obj_t *obj, lv_text_align_t align);
void setObjTextFont(lv_obj_t *obj, const lv_font_t *font);
void setObjTextColor(lv_obj_t *obj, lv_color_t color);
// The selector is LV_PART_MAIN, or LV_PART_INDICATOR for a bar's fill.
void setObjBgColor(lv_obj_t *obj, lv_color_t color, lv_style_selector_t selector = LV_PART_MAIN);

// Plain object helpers
lv_obj_t *makePanel(lv_obj_t *parent, int x, int y, int w, int h, int radius, lv_color_t border, lv_color_t bg,
                    bool filled);
lv_obj_t *makeRect(lv_obj_t *parent, const cyd_layout::Item &item, lv_color_t border);
lv_obj_t *makeFilledRect(lv_obj_t *parent, const cyd_layout::Item &item, lv_color_t border, lv_color_t bg);
lv_obj_t *makeLineBox(lv_obj_t *parent, const cyd_layout::Item &item, lv_color_t color);
lv_obj_t *makeHLine(lv_obj_t *parent, int x, int y, int w, lv_color_t color);
lv_obj_t *makeVLine(lv_obj_t *parent, int x, int y, int h, lv_color_t color);

// Labels bound to layout items. The item's anchor and font determine
// placement; maxWidth (when set) centers the label like the TFT firmware.
lv_obj_t *makeLabel(lv_obj_t *parent, const cyd_layout::Item &item, const char *text, lv_color_t color);
lv_obj_t *makeLabelFont(lv_obj_t *parent, const cyd_layout::Item &item, const char *text, lv_color_t color,
                        const lv_font_t *font);
// Free-position label (TFT drawString equivalent, datum via anchor code)
lv_obj_t *makeLabelAt(lv_obj_t *parent, int x, int y, const char *text, lv_color_t color, const lv_font_t *font,
                      uint8_t anchor = 0);
// makeLabelAt clips every label to one line by design, so a width set after it
// cannot make the text wrap. Use this for a full sentence that has to wrap
// inside a known box instead of running off both edges.
void wrapLabel(lv_obj_t *label, int x, int y, int width, lv_text_align_t align = LV_TEXT_ALIGN_CENTER);
// Shrinks the font until the text fits item.maxWidth (drawCenteredFittedText)
void setFittedText(lv_obj_t *label, const cyd_layout::Item &item, const char *text, const lv_font_t *preferred);

// Fixes a label's font and box once from a worst-case template (e.g. "000")
// so later value updates never resize or reflow anything — with tabular
// digits the text then repaints strictly in place. Update the value with
// plain setLabelText afterwards.
void configureFittedLabel(lv_obj_t *label, const cyd_layout::Item &item, const char *tmpl,
                          const lv_font_t *preferred);

// configureFittedLabel sized for one fixed worst case, which forces a readout
// to wear the font its longest possible value needs. This picks the font from
// the value in hand instead, so "99" stays large and "100" steps down a tier,
// and it only refits when the character count changes — within a width class
// updates still repaint in place.
void setScaledValueText(lv_obj_t *label, const cyd_layout::Item &item, const char *text,
                        const lv_font_t *preferred);

// Crisp 16x16 two-state icon from cyd_icons_1bit.h, tinted fg (transparent bg)
lv_obj_t *makeIcon(lv_obj_t *parent, int x, int y, CydIconId icon, lv_color_t fg);
lv_obj_t *makeLayoutIcon(lv_obj_t *parent, const cyd_layout::Item &item, CydIconId icon, lv_color_t fg);
void setIconSource(lv_obj_t *image, CydIconId icon, lv_color_t fg);
// Frees cached icon descriptors. Call only right before building a new
// screen: live widgets referencing the cache must never render again.
void clearIconCache();

// Battery outline icon with level fill
struct BatteryWidget {
  lv_obj_t *root;
  lv_obj_t *fill;
  int innerW;
  int lastPercent;
};
BatteryWidget makeBattery(lv_obj_t *parent, const cyd_layout::Item &item, lv_color_t fg);
void setBatteryLevel(BatteryWidget &widget, int percent, lv_color_t goodColor);

// Segmented battery: an outlined body and terminal holding discrete blocks, one
// per step of charge. A block count that divides 100 (5 blocks = 20 % each)
// reads at a glance in a way a sliding fill does not. Fewer blocks buy width:
// the interior needs count*blockW + (count-1) px, plus 7 px of chrome.
// Colors are fixed by the widget (cyd_ui::kBattery* in ui_style.h), not the
// theme, and follow the dashboard's light/dark appearance at build time.
constexpr int SEG_BATTERY_MAX_BLOCKS = 12;
struct SegBatteryWidget {
  lv_obj_t *blocks[SEG_BATTERY_MAX_BLOCKS];
  int count;
  int lastLit;
  uint32_t lastColor;
  bool light;
  bool blinking;
};
SegBatteryWidget makeSegBattery(lv_obj_t *parent, const cyd_layout::Item &item, int blocks = 10);
void setSegBatteryLevel(SegBatteryWidget &widget, int percent);

// Segmented meter. Blocks light left to right, but each block's colour is
// fixed by its position on the scale, so the same block always means the same
// reading — it shows how hard something is working the way an instrument does,
// rather than as a bar whose colour tells you nothing.
constexpr int SEG_METER_MAX_BLOCKS = 40;
struct SegMeterWidget {
  lv_obj_t *blocks[SEG_METER_MAX_BLOCKS];
  lv_color_t colors[SEG_METER_MAX_BLOCKS];  // lit colour per block
  lv_color_t unlitColors[SEG_METER_MAX_BLOCKS];
  int count;
  int lastLit;
};
SegMeterWidget makeSegMeter(lv_obj_t *parent, const cyd_layout::Item &item, lv_color_t low, lv_color_t mid,
                            lv_color_t high, int blocks = 20);
void setSegMeterValue(SegMeterWidget &meter, int value, int maxValue);
void setSegMeterColors(SegMeterWidget &meter, lv_color_t lit, lv_color_t unlit);

// Segmented ring: the segmented meter's blocks bent round a dial. The look is the
// bar meters' own -- solid blocks about two pixels apart, lit in the ring's colour
// and unlit as a dark ghost of it -- but every block is the same wedge, so the ring
// reads as one instrument. One custom-drawn object carries the whole ring (no
// object per block), and a new value invalidates only the blocks that flip.
//
// Block width and gap are the same in pixels on every ring (about 3.25 and 2.25 px)
// along the ring's centre line, so rings of different radii look alike and only the
// block count follows the radius. lv_draw_arc takes whole degrees, so
// the pitch and gap are rounded to degrees once and every block of a ring is then
// identical. Angles are degrees clockwise from 3 o'clock.
struct SegRingGeometry {
  int16_t startDeg;   // leading edge of the first block
  int16_t extentDeg;  // from that edge to the last block's trailing edge
  uint8_t count;
  uint8_t pitchDeg;   // one block plus one gap
  uint8_t blockDeg;
};
// `sweepDeg` is the most the ring may span; the blocks are centred on 12 o'clock.
SegRingGeometry segRingGeometry(int radius, int thickness, int sweepDeg);
// The thickness a ring of this radius is given when the caller has no reason to choose:
// it grows with the dial, a sixth of the radius plus a pixel and a third, so a big dial
// gets taller blocks than a small one (7 px at radius 34, 9 at 48, 11 at 59) while block
// width and spacing stay the same. A fifth of the radius would be truer to the ratio but
// leaves the power gauge's digits 2 px from the ring, and whole-degree rounding then makes
// the blocks of the largest ring visibly wider than the others.
int segRingThickness(int radius);

struct SegRingWidget {
  lv_obj_t *obj;
  lv_color_t lit;
  lv_color_t unlit;
  int16_t cx, cy;     // dial centre, screen coordinates
  int16_t radius;     // outer edge of the blocks
  int16_t startDeg;
  int16_t extentDeg;
  uint8_t thickness;  // radial length of a block
  uint8_t count;
  uint8_t pitchDeg;
  uint8_t blockDeg;
  int8_t litBlocks;   // -1 until the first value
  uint8_t majorExtra; // px the major blocks reach further in than the others
  uint8_t majorSteps; // majors fall at k/majorSteps of the ring, k = 0..majorSteps; 0 for none
  int16_t fillBottom; // the disc is not drawn from this screen row down
  bool hasFill;
  lv_color_t fill;    // the disc inside the blocks
};
// `ring` is the caller's storage and the draw callback keeps a pointer to it, so it
// must outlive the object (a static, like the other dashboard widgets).
void makeSegRing(SegRingWidget &ring, lv_obj_t *parent, int cx, int cy, int radius, int thickness, int sweepDeg,
                 lv_color_t lit, lv_color_t unlit);
void setSegRingValue(SegRingWidget &ring, int value, int maxValue);
void setSegRingColors(SegRingWidget &ring, lv_color_t lit, lv_color_t unlit);
// A disc behind the ring, out to the blocks' outer edge (drawn by the ring, so it costs no object),
// not drawn from screen row `bottomY` down (a bar below it, drawn over the ring, stays clear).
void setSegRingFill(SegRingWidget &ring, lv_color_t fill, int bottomY);
// Every block at k/steps of the ring (k = 0..steps, the dual gauge's longer ticks) reaches `extraPx`
// further in than the rest. Call once, right after makeSegRing.
void setSegRingMajors(SegRingWidget &ring, int extraPx, int steps);

// Segmented arc gauge (drawGaugeScale/updateGaugeArc): 260deg sweep from 140deg
struct ArcGauge {
  lv_obj_t *arc;
  lv_meter_indicator_t *indic;  // set when the gauge is a meter, else NULL
  int maxValue;
  int lastValue;
};
ArcGauge makeSegGauge(lv_obj_t *parent, int cx, int cy, int r, int maxValue, lv_color_t active,
                      lv_color_t inactive, lv_color_t tickMajor, lv_color_t tickMinor);
ArcGauge makeSimpleArc(lv_obj_t *parent, int cx, int cy, int r, int maxValue, int width, lv_color_t active,
                       lv_color_t inactive, int startDeg = 140, int sweepDeg = 260);
void setArcValue(ArcGauge &gauge, int value);

// Horizontal bar row (drawLayoutBarRow): outlined bar with fill
lv_obj_t *makeBarFrame(lv_obj_t *parent, const cyd_layout::Item &frame, lv_color_t color);
void setBarValue(lv_obj_t *bar, int amount, int maxAmount);

// Screen container with black background, no scroll/padding
lv_obj_t *makeScreen();
