#pragma once
#include <Arduino.h>

// Two-state indexed masks generated by tools/convert_icons_1bit.py.
// Pixel packing is MSB first; 0 is transparent and 1 is fully opaque.
constexpr int CYD_ICON_SIZE = 16;
constexpr int CYD_ICON_BYTES = 32;

enum CydIconId {
  CYD_ICON_SPEED,
  CYD_ICON_BATTERY,
  CYD_ICON_CURRENT,
  CYD_ICON_POWER,
  CYD_ICON_EFFICIENCY,
  CYD_ICON_TEMP_MOTOR,
  CYD_ICON_TEMP_ESC,
  CYD_ICON_TRIP,
  CYD_ICON_ODO,
  CYD_ICON_AVG_SPEED,
  CYD_ICON_UPTIME,
  CYD_ICON_BIKE_UPTIME,
  CYD_ICON_ESC_TEMP,
  CYD_ICON_VOLTAGE,
  CYD_ICON_AMPERAGE,
  CYD_ICON_WATTS,
  CYD_ICON_DISTANCE,
  CYD_ICON_NAV,
  CYD_ICON_BLUETOOTH,
  CYD_ICON_WIFI,
  CYD_ICON_SD_CARD,
  CYD_ICON_SETTINGS,
  CYD_ICON_WARNING,
  CYD_ICON_FAULT,
  CYD_ICON_LIGHTS,
  CYD_ICON_COUNT
};

extern const uint8_t *const cydIconData[CYD_ICON_COUNT] PROGMEM;
