from __future__ import annotations

import argparse
import math
from pathlib import Path

from PIL import Image


ICON_FILES = [
    ("speed", "speedometer.png"),
    ("battery", "battery.png"),
    ("current", "amps_gauge.png"),
    ("power", "heartbeat.png"),
    ("efficiency", "efficiency.png"),
    ("temp_motor", "thermometer.png"),
    ("temp_esc", "chip.png"),
    ("trip", "trip.png"),
    ("odo", "odo.png"),
    ("avg_speed", "speedometer.png"),
    ("uptime", "clock.png"),
    ("bike_uptime", "bike.png"),
    ("esc_temp", "chip.png"),
    ("voltage", "voltage.png"),
    ("amperage", "amps_gauge.png"),
    ("watts", "heartbeat.png"),
    ("distance", "navigation.png"),
    ("nav", "navigation.png"),
    ("bluetooth", "bluetooth.png"),
    ("wifi", "wifi.png"),
    ("sd_card", "sd_card.png"),
    ("settings", "wrench.png"),
    ("warning", "warning_filled.png"),
    ("fault", "warning_outline.png"),
    ("lights", "headlight.png"),
]


def pack_1bit(image: Image.Image) -> list[int]:
    pixels = image.load()
    width, height = image.size
    row_bytes = math.ceil(width / 8)
    data = [0] * (row_bytes * height)
    for y in range(height):
        for x in range(width):
            red, green, blue, alpha = pixels[x, y]
            visible = alpha >= 128 and max(red, green, blue) >= 128
            if visible:
                data[y * row_bytes + x // 8] |= 1 << (7 - x % 8)
    return data


def preview_from_1bit(data: list[int], size: int) -> Image.Image:
    out = Image.new("RGBA", (size, size), (255, 255, 255, 0))
    pixels = out.load()
    row_bytes = math.ceil(size / 8)
    for y in range(size):
        for x in range(size):
            if data[y * row_bytes + x // 8] & (1 << (7 - x % 8)):
                pixels[x, y] = (255, 255, 255, 255)
    return out


def bytes_as_cpp(data: list[int]) -> str:
    lines = []
    for start in range(0, len(data), 12):
        lines.append("  " + ", ".join(f"0x{value:02X}" for value in data[start : start + 12]) + ",")
    return "\n".join(lines)


def write_header(path: Path, icon_names: list[str], size: int) -> None:
    bytes_per_icon = math.ceil(size / 8) * size
    lines = [
        "#pragma once",
        "#include <Arduino.h>",
        "",
        "// Two-state indexed masks generated by tools/convert_icons_1bit.py.",
        "// Pixel packing is MSB first; 0 is transparent and 1 is fully opaque.",
        f"constexpr int CYD_ICON_SIZE = {size};",
        f"constexpr int CYD_ICON_BYTES = {bytes_per_icon};",
        "",
        "enum CydIconId {",
    ]
    lines.extend(f"  CYD_ICON_{name.upper()}," for name in icon_names)
    lines.extend(["  CYD_ICON_COUNT", "};", ""])
    lines.extend(["extern const uint8_t *const cydIconData[CYD_ICON_COUNT] PROGMEM;", ""])
    path.write_text("\n".join(lines), encoding="utf-8")


def write_source(path: Path, icons: list[tuple[str, list[int]]], size: int, header_name: str) -> int:
    lines = [
        f'#include "{header_name}"',
        "",
        "// Generated file. Re-run tools/convert_icons_1bit.py after editing icon PNGs.",
        "",
    ]
    stored: list[tuple[str, list[int]]] = []
    symbols: dict[tuple[int, ...], str] = {}
    icon_symbols: list[str] = []
    for name, data in icons:
        key = tuple(data)
        symbol = symbols.get(key)
        if symbol is None:
            symbol = name
            symbols[key] = symbol
            stored.append((symbol, data))
        icon_symbols.append(symbol)

    for name, data in stored:
        lines.extend(
            [
                f"static const uint8_t icon_{name}_{size}_1bit[] PROGMEM = {{",
                bytes_as_cpp(data),
                "};",
                "",
            ]
        )
    lines.append("const uint8_t *const cydIconData[CYD_ICON_COUNT] PROGMEM = {")
    lines.extend(f"  icon_{symbol}_{size}_1bit," for symbol in icon_symbols)
    lines.extend(["};", ""])
    path.write_text("\n".join(lines), encoding="utf-8")
    return len(stored)


def convert(args: argparse.Namespace) -> None:
    source_dir = Path(args.input)
    if not source_dir.is_dir():
        raise SystemExit(f"Icon source must be a directory: {source_dir}")

    preview_dir = Path(args.preview_dir) if args.preview_dir else None
    if preview_dir:
        preview_dir.mkdir(parents=True, exist_ok=True)
    icons: list[tuple[str, list[int]]] = []
    for name, filename in ICON_FILES:
        path = source_dir / filename
        if not path.exists():
            raise SystemExit(f"Missing icon source: {path}")
        image = Image.open(path).convert("RGBA")
        if image.size != (args.icon_size, args.icon_size):
            raise SystemExit(
                f"{path} must be {args.icon_size}x{args.icon_size}, got {image.size[0]}x{image.size[1]}"
            )
        packed = pack_1bit(image)
        icons.append((name, packed))
        if preview_dir:
            preview_from_1bit(packed, args.icon_size).save(preview_dir / f"{name}_{args.icon_size}_1bit.png")

    header = Path(args.output_header)
    source = Path(args.output_source)
    write_header(header, [name for name, _ in icons], args.icon_size)
    stored_count = write_source(source, icons, args.icon_size, header.name)
    bytes_per_icon = math.ceil(args.icon_size / 8) * args.icon_size
    print(f"Wrote {header}")
    print(f"Wrote {source}")
    if preview_dir:
        print(f"Wrote previews to {preview_dir}")
    print(
        f"{len(icons)} icon IDs, {stored_count} unique masks, "
        f"{bytes_per_icon} bytes each ({bytes_per_icon * stored_count} bytes total)"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Convert 16x16 CYD icon PNGs into 1-bit indexed PROGMEM masks.")
    parser.add_argument("input", nargs="?", default="preview_output/icons16")
    parser.add_argument("--output-header", default="include/cyd_icons_1bit.h")
    parser.add_argument("--output-source", default="src/lvgl_app/cyd_icons_1bit.cpp")
    parser.add_argument("--preview-dir", help="Optional directory for decoded PNG verification previews")
    parser.add_argument("--icon-size", type=int, default=16)
    convert(parser.parse_args())


if __name__ == "__main__":
    main()
