from __future__ import annotations

from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "preview_output" / "lvgl"
OUTPUT = ROOT / "include" / "cyd_dash_thumbnails_4bit.h"
# A 2x2 page gives each 4:3 dashboard preview substantially more room. The
# direct-color captures are packed back-to-back in one flash array and exposed
# through individual descriptors. Only four allocation-free image widgets are
# alive on a page, while no empty card spacing is stored in flash.
THUMB_WIDTH = 124
THUMB_HEIGHT = 93

# DashboardMode order. The grid captions remain localized at runtime; these
# source captures intentionally stay English so only one flash asset set is
# required for every language.
SOURCES = [
    "01_cyber_hud",
    "02_dual_gauge",
    "03_simple",
    "04_bar_graph",
    "05_motor_data",
    "06_pixel_gauge",
    "07_large_tiles",
    "08_big_readout",
    "09_redline",
    "10_trace",
    "11_minimal_ride",
    "12_efficiency",
]


def bytes_as_cpp(data: bytes) -> str:
    rows = []
    for start in range(0, len(data), 16):
        rows.append("  " + ", ".join(f"0x{value:02X}" for value in data[start : start + 16]) + ",")
    return "\n".join(rows)


def encode_thumbnail(path: Path, force_black_canvas: bool = False) -> bytes:
    with Image.open(path) as source:
        image = source.convert("RGB")
    if force_black_canvas:
        canvas = image.getpixel((0, 0))
        image.putdata([(0, 0, 0) if pixel == canvas else pixel for pixel in image.getdata()])
    image = image.resize((THUMB_WIDTH, THUMB_HEIGHT), Image.Resampling.LANCZOS)
    # LV_COLOR_16_SWAP=1 stores RGB565 in high-byte/low-byte order.  A single
    # direct-color array requires no indexed decoder state or palette allocation.
    data = bytearray()
    for red, green, blue in image.getdata():
        rgb565 = ((red & 0xF8) << 8) | ((green & 0xFC) << 3) | (blue >> 3)
        data.extend((rgb565 >> 8, rgb565 & 0xFF))
    return bytes(data)


def main() -> int:
    missing = [name for name in SOURCES if not (SOURCE / f"{name}.png").exists()]
    if missing:
        raise FileNotFoundError(f"Render English LVGL previews first; missing: {', '.join(missing)}")

    data = b"".join(
        encode_thumbnail(SOURCE / f"{name}.png", force_black_canvas=name == "11_minimal_ride")
        for name in SOURCES
    )
    bytes_per_thumb = THUMB_WIDTH * THUMB_HEIGHT * 2
    size = bytes_per_thumb * len(SOURCES)
    lines = [
        "#pragma once",
        "#include <Arduino.h>",
        "#include <lvgl.h>",
        "",
        "// Generated by tools/generate_dash_thumbnails.py from the English native LVGL previews.",
        "// Direct RGB565 previews avoid indexed-image decoder and palette allocations.",
        f"constexpr int CYD_DASH_THUMB_WIDTH = {THUMB_WIDTH};",
        f"constexpr int CYD_DASH_THUMB_HEIGHT = {THUMB_HEIGHT};",
        f"constexpr int CYD_DASH_THUMB_BYTES = {bytes_per_thumb};",
        f"constexpr int CYD_DASH_THUMBS_BYTES = {size};",
        f"constexpr int CYD_DASH_THUMB_COUNT = {len(SOURCES)};",
        "",
        "const uint8_t dash_thumb_grid[] PROGMEM = {",
        bytes_as_cpp(data),
        "};",
    ]
    for index in range(len(SOURCES)):
        lines.extend(
            [
                f"const lv_img_dsc_t dash_thumb_{index}_dsc = {{",
                "  {LV_IMG_CF_TRUE_COLOR, 0, 0, CYD_DASH_THUMB_WIDTH, CYD_DASH_THUMB_HEIGHT},",
                "  CYD_DASH_THUMB_BYTES,",
                f"  dash_thumb_grid + CYD_DASH_THUMB_BYTES * {index}",
                "};",
            ]
        )
    lines.extend(
        [
            "const lv_img_dsc_t *const cydDashThumbs[] = {",
            "  " + ", ".join(f"&dash_thumb_{index}_dsc" for index in range(len(SOURCES))),
            "};",
            "",
        ]
    )
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUTPUT} ({len(SOURCES)} packed {THUMB_WIDTH}x{THUMB_HEIGHT} previews, {size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
