#!/usr/bin/env python3
"""Turn CHANGELOG.md into the header the firmware compiles in.

CHANGELOG.md is the single source. This writes src/lvgl_app/firmware_changelog.h
from the newest entries; `--check` verifies the header is current without
writing, which is what CI runs so the two cannot drift apart.

Only the newest MAX_ENTRIES are compiled in: the display gives the changelog a
single page holding exactly that many, and an unbounded list would grow flash
for no one's benefit.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "CHANGELOG.md"
HEADER = ROOT / "src" / "lvgl_app" / "firmware_changelog.h"

MAX_ENTRIES = 4
# At Rajdhani 12 the 300 px panel holds ~46 characters a line and a compact
# entry gets two wrapped lines, so 90 is the most that fits without a third.
MAX_TITLE = 30
MAX_SUMMARY = 90

ENTRY = re.compile(r"^##\s+(\d{4}-\d{2}-\d{2})\s+[—-]\s+(.+?)\s*$")


class ChangelogError(RuntimeError):
    pass


def parse(markdown: str) -> list[tuple[str, str, str]]:
    """Returns [(date, title, summary)] in file order (newest first)."""
    entries: list[tuple[str, str, list[str]]] = []
    in_code_fence = False
    for line in markdown.splitlines():
        if line.startswith("```"):
            in_code_fence = not in_code_fence
            continue
        if in_code_fence:
            continue
        match = ENTRY.match(line)
        if match:
            entries.append((match.group(1), match.group(2), []))
        elif entries and line.strip():
            entries[-1][2].append(line.strip())

    parsed = []
    for date, title, body in entries:
        summary = " ".join(body)
        if not summary:
            raise ChangelogError(f"entry {date} '{title}' has no summary")
        parsed.append((date, title, summary))
    if not parsed:
        raise ChangelogError("no entries found; check the '## YYYY-MM-DD — Title' format")

    dates = [entry[0] for entry in parsed]
    if dates != sorted(dates, reverse=True):
        raise ChangelogError("entries must be newest first")
    return parsed


def escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def truncate(text: str, limit: int) -> str:
    """Trim on a word boundary. ASCII dots only: the Rajdhani font the display
    uses has no U+2026 glyph, so a real ellipsis renders as a missing-glyph box."""
    if len(text) <= limit:
        return text
    clipped = text[: limit - 3]
    spaced = clipped.rsplit(" ", 1)[0]
    return (spaced if len(spaced) >= limit // 2 else clipped).rstrip(" ,.;:") + "..."


def render(entries: list[tuple[str, str, str]]) -> str:
    shown = entries[:MAX_ENTRIES]
    lines = [
        "// Generated by tools/generate_changelog_header.py from CHANGELOG.md.",
        "// Do not edit by hand: edit CHANGELOG.md and rerun the script.",
        "//",
        "// English only, unlike the rest of the interface. Translating changelog",
        "// entries six ways is not worth hand-maintaining, so the headings around",
        "// them are localised and the entries themselves are not.",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "struct FirmwareChangelogEntry {",
        "  const char *date;",
        "  const char *title;",
        "  const char *summary;",
        "};",
        "",
        "static const FirmwareChangelogEntry kFirmwareChangelog[] = {",
    ]
    for date, title, summary in shown:
        # Truncation is legible but ugly, and it is always avoidable by editing
        # the entry, so say so rather than quietly shipping a clipped summary.
        if len(title) > MAX_TITLE:
            print(f"warning: {date} title is {len(title)} chars, truncating to {MAX_TITLE}", file=sys.stderr)
        if len(summary) > MAX_SUMMARY:
            print(f"warning: {date} summary is {len(summary)} chars, truncating to {MAX_SUMMARY}", file=sys.stderr)
        lines.append("    {")
        lines.append(f'        "{escape(date)}",')
        lines.append(f'        "{escape(truncate(title, MAX_TITLE))}",')
        lines.append(f'        "{escape(truncate(summary, MAX_SUMMARY))}",')
        lines.append("    },")
    lines.append("};")
    lines.append("")
    lines.append(
        f"static constexpr uint8_t kFirmwareChangelogCount = "
        f"sizeof(kFirmwareChangelog) / sizeof(kFirmwareChangelog[0]);"
    )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the generated header is out of date instead of writing it",
    )
    args = parser.parse_args()

    try:
        entries = parse(SOURCE.read_text(encoding="utf-8"))
    except (OSError, ChangelogError) as error:
        print(f"CHANGELOG.md: {error}", file=sys.stderr)
        return 2

    wanted = render(entries)
    current = HEADER.read_text(encoding="utf-8") if HEADER.exists() else None

    if args.check:
        if current != wanted:
            print(
                f"{HEADER.relative_to(ROOT)} is out of date.\n"
                f"Run: python tools/generate_changelog_header.py",
                file=sys.stderr,
            )
            return 1
        print(f"{HEADER.relative_to(ROOT)} matches CHANGELOG.md")
        return 0

    if current == wanted:
        print(f"{HEADER.relative_to(ROOT)} already up to date")
        return 0
    HEADER.write_text(wanted, encoding="utf-8", newline="\n")
    print(f"Wrote {HEADER.relative_to(ROOT)} ({min(len(entries), MAX_ENTRIES)} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
