from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FONT_DIR = ROOT / "src" / "lvgl_app"
UI_COMMON = FONT_DIR / "ui_common.cpp"
OUT = ROOT / "tools" / "lvgl_font_metrics.json"

FONT_FILES = {
    "rajdhani10": "lv_font_rajdhani_10.c",
    "rajdhani12": "lv_font_rajdhani_12.c",
    "rajdhani14": "lv_font_rajdhani_14.c",
    "rajdhani16": "lv_font_rajdhani_16.c",
    "rajdhani20": "lv_font_rajdhani_20.c",
    "rajdhani24": "lv_font_rajdhani_24.c",
    "rajdhani36": "lv_font_rajdhani_36.c",
    "speed48": "lv_font_speed48.c",
    "speed72": "lv_font_speed72.c",
    "speed96": "lv_font_speed96.c",
}

FONT_NAME_TO_ID = {
    "lv_font_speed96": "speed96",
    "lv_font_speed72": "speed72",
    "lv_font_speed48": "speed48",
    "lv_font_rajdhani_10": "rajdhani10",
    "lv_font_rajdhani_12": "rajdhani12",
    "lv_font_rajdhani_14": "rajdhani14",
    "lv_font_rajdhani_16": "rajdhani16",
    "lv_font_rajdhani_20": "rajdhani20",
    "lv_font_rajdhani_24": "rajdhani24",
    "lv_font_rajdhani_36": "rajdhani36",
    "lv_font_montserrat_10": "rajdhani12",
    "lv_font_montserrat_12": "rajdhani12",
    "lv_font_montserrat_14": "rajdhani14",
    "lv_font_montserrat_16": "rajdhani16",
    "lv_font_montserrat_20": "rajdhani20",
    "lv_font_montserrat_24": "rajdhani24",
    "lv_font_montserrat_28": "rajdhani24",
    "lv_font_montserrat_36": "rajdhani36",
    "lv_font_montserrat_48": "rajdhani36",
}

def parse_firmware_font_tiers() -> tuple[list[str], dict[str, str], dict[str, str]]:
    text = UI_COMMON.read_text(encoding="utf-8", errors="ignore")
    block = re.search(r"static const FontEntry kFonts\[\]\s*=\s*\{(.*?)\n\};", text, re.S)
    if not block:
        raise RuntimeError(f"Could not find kFonts[] in {UI_COMMON}")
    rows = re.findall(r"\{\s*(\d+)\s*,\s*&([A-Za-z0-9_]+)\s*\}", block.group(1))
    available = sorted({int(px) for px, _ in rows})
    tier_map: dict[str, str] = {}
    threshold_map: dict[str, str] = {}
    for px, font_name in rows:
        key = f"F{px}"
        font_id = FONT_NAME_TO_ID.get(font_name)
        if not font_id:
            raise RuntimeError(f"Unhandled LVGL font in kFonts[]: {font_name}")
        tier_map[key] = font_id
        threshold_map[key] = key
    return [f"F{px}" for px in available], tier_map, threshold_map


def parse_font(path: Path) -> dict:
    text = path.read_text(encoding="utf-8", errors="ignore")
    size_match = re.search(r"Opts:.*?--size\s+(\d+)", text)
    if not size_match:
        raise RuntimeError(f"Could not find lv_font_conv --size in {path}")
    source_size = int(size_match.group(1))
    line_height = int(re.search(r"\.line_height\s*=\s*(\d+)", text).group(1))
    base_line = int(re.search(r"\.base_line\s*=\s*(\d+)", text).group(1))
    glyph_block = re.search(r"glyph_dsc\[\]\s*=\s*\{(.*?)\n\};", text, re.S).group(1)
    glyphs = []
    for m in re.finditer(
        r"\.adv_w\s*=\s*(\d+),\s*\.box_w\s*=\s*(\d+),\s*\.box_h\s*=\s*(\d+),\s*\.ofs_x\s*=\s*(-?\d+),\s*\.ofs_y\s*=\s*(-?\d+)",
        glyph_block,
    ):
        glyphs.append(
            {
                "adv": int(m.group(1)) / 16,
                "box_w": int(m.group(2)),
                "box_h": int(m.group(3)),
                "ofs_x": int(m.group(4)),
                "ofs_y": int(m.group(5)),
            }
        )

    cmap = re.search(
        r"\.range_start\s*=\s*(\d+),\s*\.range_length\s*=\s*(\d+),\s*\.glyph_id_start\s*=\s*(\d+)",
        text,
    )
    start = int(cmap.group(1))
    length = int(cmap.group(2))
    glyph_id_start = int(cmap.group(3))
    widths = {}
    for i in range(length):
        glyph_index = glyph_id_start + i
        if glyph_index < len(glyphs):
            widths[chr(start + i)] = round(glyphs[glyph_index]["adv"], 3)
    return {
        "source": path.name,
        "sourceSize": source_size,
        "lineHeight": line_height,
        "baseLine": base_line,
        "widths": widths,
    }


def main() -> None:
    fonts = {name: parse_font(FONT_DIR / file_name) for name, file_name in FONT_FILES.items()}
    available_tiers, tier_map, threshold_map = parse_firmware_font_tiers()
    payload = {
        "comment": "Generated by tools/generate_lvgl_font_metrics.py from src/lvgl_app/lv_font_*.c.",
        "family": {
            "ui": "Rajdhani SemiBold",
            "speed": "Rajdhani Bold",
            "fallbackCss": '"Rajdhani Local", "Arial Narrow", "Segoe UI", sans-serif',
        },
        "availableTiers": available_tiers,
        "tiers": tier_map,
        "thresholds": threshold_map,
        "fonts": fonts,
    }
    OUT.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
