from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LAYOUT = ROOT / "tools" / "layout.json"
HEADER = ROOT / "include" / "cyd_layout_generated.h"


def ident(value: str) -> str:
    text = re.sub(r"[^0-9A-Za-z]+", "_", value)
    text = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", text)
    text = re.sub(r"_+", "_", text).strip("_").upper()
    return text or "ITEM"


def font_number(value: str | None) -> int:
    if not value:
        return 0
    match = re.fullmatch(r"F(\d+)", value)
    return int(match.group(1)) if match else 0


def anchor_number(value: str | None) -> int:
    return {"la": 0, "mm": 1, "ra": 2, "tc": 3, "tr": 4, "tl": 0}.get(value or "la", 0)


def type_number(value: str | None) -> int:
    return {
        "rect": 1,
        "rrect": 2,
        "line": 3,
        "ellipse": 4,
        "icon": 5,
        "battery": 6,
        "arcGauge": 7,
        "continuousArc": 8,
        "arcBar": 9,
        "tickGauge": 10,
        "segBar": 11,
    }.get(value or "", 0)


def bbox_from_points(points: list[list[int]]) -> tuple[int, int, int, int]:
    xs = [p[0] for p in points]
    ys = [p[1] for p in points]
    return min(xs), min(ys), max(xs) - min(xs), max(ys) - min(ys)


def item_values(item: dict) -> dict[str, int]:
    values = {
        "x": int(item.get("x", 0)),
        "y": int(item.get("y", 0)),
        "w": int(item.get("w", 0)),
        "h": int(item.get("h", 0)),
        "radius": int(item.get("radius", 0)),
        "cx": int(item.get("cx", 0)),
        "cy": int(item.get("cy", 0)),
        "r": int(item.get("r", 0)),
        "maxValue": int(item.get("max", 0)),
        "maxWidth": int(item.get("max_w", 0)),
        "font": font_number(item.get("font")),
        "anchor": anchor_number(item.get("anchor")),
        "type": type_number(item.get("type")),
    }
    if item.get("type") == "line" and "points" in item:
        values["x"], values["y"], values["w"], values["h"] = bbox_from_points(item["points"])
    if "fit" in item and item["fit"]:
        values["font"] = font_number(item["fit"][0])
    return values


def write_header(layout: dict) -> None:
    HEADER.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = [
        "#pragma once",
        "#include <Arduino.h>",
        "",
        "// Generated by tools/generate_layout_header.py from tools/layout.json.",
        "// Do not edit by hand; update layout.json with the editor, then regenerate.",
        "",
        "namespace cyd_layout {",
        "",
        "struct Item {",
        "  int16_t x;",
        "  int16_t y;",
        "  int16_t w;",
        "  int16_t h;",
        "  int16_t radius;",
        "  int16_t cx;",
        "  int16_t cy;",
        "  int16_t r;",
        "  int16_t maxValue;",
        "  int16_t maxWidth;",
        "  uint8_t font;",
        "  uint8_t anchor;",
        "  uint8_t type;",
        "};",
        "",
    ]

    screens = layout["screens"]
    for screen_id, screen in screens.items():
        prefix = ident(screen.get("prefix") or screen_id)
        for item in screen.get("items", []):
            name = f"{prefix}_{ident(item['id'])}"
            v = item_values(item)
            lines.append(
                f"constexpr Item {name} = "
                f"{{{v['x']}, {v['y']}, {v['w']}, {v['h']}, {v['radius']}, "
                f"{v['cx']}, {v['cy']}, {v['r']}, {v['maxValue']}, {v['maxWidth']}, "
                f"{v['font']}, {v['anchor']}, {v['type']}}};"
            )
        lines.append("")

    lines.append("}  // namespace cyd_layout")
    HEADER.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def main() -> None:
    layout = json.loads(LAYOUT.read_text(encoding="utf-8"))
    write_header(layout)
    print(f"Wrote {HEADER}")


if __name__ == "__main__":
    main()
